blank_issues_enabled: false
contact_links:
  - name: Читать README
    url: https://github.com/JohNick-Mods/max-mod-johnick#readme
    about: Инструкция по установке, описание всех тумблеров, FAQ по уведомлениям и Цифровому ID
